global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'netview'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Docker Desktop
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Alternative for Linux Docker
  - job_name: 'netview-linux'
    static_configs:
      - targets: ['172.17.0.1:8000']  # Docker bridge IP
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
